services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - picpay_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: picpay_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - picpay_network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: picpay_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: picpay_db
      POSTGRES_USER: picpay_user
      POSTGRES_PASSWORD: picpay_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - picpay_network

  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay_php_cli
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - picpay_network
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"

networks:
  picpay_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

